CREATE TABLE IF NOT EXISTS user ( email VARCHAR(256) PRIMARY KEY, salt VARCHAR(256) NOT NULL, password VARBINARY(256) NOT NULL);
CREATE TABLE IF NOT EXISTS instrument ( id VARCHAR(256) PRIMARY KEY, type VARCHAR(256), make VARCHAR(256), serial VARCHAR(256), product_no VARCHAR(256), description VARCHAR(256) );
CREATE TABLE IF NOT EXISTS musician ( id VARCHAR(256) PRIMARY KEY, first_name VARCHAR(256), last_name VARCHAR(256), has_own_instrument SMALLINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS instrument_type ( id VARCHAR(256) PRIMARY KEY, name VARCHAR(256) );
CREATE TABLE IF NOT EXISTS instrument_state ( instrument_id VARCHAR(256), date DATETIME, state TEXT, state_by_user VARCHAR(256) );
CREATE TABLE IF NOT EXISTS musician_instrument ( instrument_id VARCHAR(256), musician_id VARCHAR(256), out_at DATETIME, out_by_user VARCHAR(256), in_at DATETIME, in_by_user VARCHAR(256) );

INSERT INTO instrument_type values ('1', 'Kornett');
INSERT INTO instrument_type values ('2', 'Trompet');
INSERT INTO instrument_type values ('3', 'Klarinett');
INSERT INTO instrument_type values ('4', 'Klarinett (Bass)');
INSERT INTO instrument_type values ('5', 'Valthorn');
INSERT INTO instrument_type values ('6', 'Tuba');
INSERT INTO instrument_type values ('7', 'Baryton');
INSERT INTO instrument_type values ('8', 'Horn');
INSERT INTO instrument_type values ('9', 'Horn (Alt)');
INSERT INTO instrument_type values ('10', 'Horn (Tenor)');
INSERT INTO instrument_type values ('11', 'Horn (Flygel)');
INSERT INTO instrument_type values ('12', 'Obo');
INSERT INTO instrument_type values ('13', 'Fagott');
INSERT INTO instrument_type values ('14', 'Fløyte');
INSERT INTO instrument_type values ('15', 'Fløyte (Piccolo)');
INSERT INTO instrument_type values ('16', 'Saksofon');
INSERT INTO instrument_type values ('17', 'Saksofon (Alt)');
INSERT INTO instrument_type values ('18', 'Saksofon (Tenor)');
INSERT INTO instrument_type values ('19', 'Trombone');
INSERT INTO instrument_type values ('20', 'Trombone (Alt)');
INSERT INTO instrument_type values ('21', 'Trombone (Tenor)');
INSERT INTO instrument_type values ('22', 'Perkusjon (Rytmisk)');
INSERT INTO instrument_type values ('23', 'Perkusjon (Melodisk)');
INSERT INTO instrument_type values ('24', 'Saksofon (Baryton)');
INSERT INTO instrument_type values ('25', 'Susafon');